# Tsinghua MOOC Caption Crawler by c7w.
# Modified by OceanS2000.
#
# classroom_id: an integer id as found in devtools

classroom_id: 30

# Also don't forget to put your cookies into './cookies' !
